<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/** @var IDme\GroupVerification\Block\Adminhtml\Dashboard\Idme $block */
// @codingStandardsIgnoreFile

?>
<?php if (count($block->getTotals()) > 0): ?>
<div class="dashboard-container-row">
    <div class="dashboard-main col-m-8 col-m-push-4">
        <header class="dashboard-item-title">
            <?php echo $block->escapeHtml(__('ID.me Statistics')); ?>
            </header>
        <div class="dashboard-totals">
            <ul class="dashboard-totals-list">
            <?php foreach ($block->getTotals() as $_total): ?>
                <li class="dashboard-totals-item">
                    <span class="dashboard-totals-label">
                    <?= $block->escapeHtml($_total['label']) ?>
                    </span>
                    <strong class="dashboard-totals-value">
                        <span class="price">
                            <?= $block->escapeHtml($_total['value'], ['span']) ?>
                        </span>
                        <span class="dashboard-totals-decimals">
                            <?= $block->escapeHtml($_total['decimals']) ?>
                        </span>
                    </strong>
                </li>
            <?php endforeach; ?>
            </ul>
        </div>
    </div>
</div>
<?php endif; ?>
