<?php /** @var \IDme\GroupVerification\Block\Adminhtml\Order\View\Tab\IDme $block */ ?>
<section class="admin__page-section order-view-account-information">
    <div class="admin__page-section-title">
        <span class="title"><?php echo $block->escapeHtml(__('ID.me Group Details')); ?></span>
    </div>
    <div class="admin__page-section-content">
        <div class="admin__page-section-item order-information">
            <div class="admin__page-section-item-content">
                <table class="admin__table-secondary order-information-table">
                    <?php foreach ($block->getIdmeInfo() as $_item): ?>
                        <tr>
                            <th><?php echo $block->escapeHtml(__($_item['label'])); ?></th>
                            <td>
                                <?php if (is_array($_item['value'])): ?>
                                    <?php foreach ($_item['value'] as $value): ?>
                                        <p><?php echo $block->escapeHtml($value); ?></p>
                                    <?php endforeach; ?>
                                <?php else: ?>
                                    <?php echo $block->escapeHtml($_item['value']); ?>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
        </div>
    </div>
</section>